# netlify.toml

[构建]
  # 如果你的项目不需要构建步骤 (纯静态 + 函数)，可以省略 publish
  # publish = "." # 假设你的 HTML/CSS/JS 文件在根目录
  functions = "netlify/functions" # 指定 Netlify 函数目录

# 配置 Edge Functions
[[边缘函数]]
  函数 = "注入环境"
  路径 = "/*"

# 配置重写规则，将 /proxy/* 的请求路由到 proxy 函数
# 这样前端的 PROXY_URL 仍然可以是 '/proxy/'
[[重定向]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat" # 将路径参数传递给函数
  状态 = 200 # 重要：这是代理，不是重定向

# 处理搜索路径格式 /s=*
[[重定向]]
  from = "/s=*"
  to = "/index.html"
  状态 = 200

# （可选）为其他静态文件设置缓存头等
# [[标题]]
#   for = "/*"
#   [标题.值]
#     # 在这里添加任何全局头文件
